force-app/main/default/objects/Submission__c/Submission__c.object-meta.xml
<CustomObject>
    <label>Submission</label>
    <nameField>
        <displayFormat>s-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Submissions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Submission__c/fields/Custom_JSON_Status__c.field-meta.xml
<CustomField>
    <fullName>Custom_JSON_Status__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Custom JSON Status</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Submission__c/fields/Message_Id__c.field-meta.xml
<CustomField>
    <fullName>Message_Id__c</fullName>
    <externalId>true</externalId>
    <label>Message Id</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Submission__c/fields/Submission_360_Status__c.field-meta.xml
<CustomField>
    <fullName>Submission_360_Status__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Submission 360 Status</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Submission__c/fields/Submission_Id__c.field-meta.xml
<CustomField>
    <fullName>Submission_Id__c</fullName>
    <externalId>true</externalId>
    <label>Submission Id</label>
    <length>50</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/classes/UploadAPIResponseProcessor.cls
public with sharing class UploadAPIResponseProcessor {
    public UploadAPIResponseProcessor() {

    }
    //force-app\main\default\classes\UploadAPIResponseProcessor.cls

    public static Sobject processJSONResponse(String JSONResponse){

        //StaticResource SR = [Select id,name,body from StaticResource where Name = 'uploadresponse'];
        String uploadresponse =  JSONResponse;
        System.debug(LoggingLevel.DEBUG, 'processJSONResponse:'+uploadresponse);
        Map<String, Object> m = (Map<String, Object>)JSON.deserializeUntyped(uploadresponse);
        String response_Id = (String)m.get('id');

        return getSubmissionRecord(response_Id);
    }

    public static Sobject getSubmissionRecord(String messageId){
     Sobject sobj = getSobjectInstance('Submission__c');
     sobj.put('Custom_JSON_Status__c',false);
     sobj.put('Message_Id__c',messageId);
     sobj.put('Submission_360_Status__c',false);
     sobj.put('Submission_Id__c','');
     //Insert sobj;
     return sobj;
    }
    public static SObject getSobjectInstance(String sobjectName){
        Schema.DescribeSobjectResult[] dsrList = Schema.describeSObjects(new List<String>{sobjectName});
        Schema.DescribeSobjectResult dsr = dsrList[0];
        return dsr.getSObjectType().newSObject();

    }
}