force-app/main/default/objects/Cognisureapi__mdt/Cognisureapi__mdt.object-meta.xml
<CustomObject>
    <label>Cognisureapi</label>
    <pluralLabel>Cognisureapis</pluralLabel>
</CustomObject>

force-app/main/default/objects/Cognisureapi__mdt/fields/Email_Message_Query_Plugin__c.field-meta.xml
<CustomField>
    <fullName>Email_Message_Query_Plugin__c</fullName>
    <description>Can be used to supply query to process email emails in the batch</description>
    <inlineHelpText>Can be used to supply query to process email emails in the batch</inlineHelpText>
    <label>Email Message Query Plugin</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Cognisureapi__mdt/fields/Submission_Query_Plugin__c.field-meta.xml
<CustomField>
    <fullName>Submission_Query_Plugin__c</fullName>
    <description>Apex Class used to supply submission query processed in batches</description>
    <label>Submission Query Plugin</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Submission__c/Submission__c.object-meta.xml
<CustomObject>
    <label>Submission</label>
    <nameField>
        <displayFormat>s-{0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Submissions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Submission__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Case</label>
    <referenceTo>Case</referenceTo>
    <relationshipLabel>Submissions</relationshipLabel>
    <relationshipName>Submissions</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/CSFileUploadAPIConsumerBatch.cls
public class CSFileUploadAPIConsumerBatch implements Database.Batchable<sObject>, Database.Stateful, Database.AllowsCallouts {
    class CSFileUploadAPIException extends Exception {
    }
    String query;
    private CognisureAPIConsumerCtrl csapi;

    public CSFileUploadAPIConsumerBatch() {
       // this.query = 'Select Id from case where createdDate = today and Id not in (select case__c from Submission__c)';
        Sobject  cognisureapimetadata = [Select Id,Email_Message_Query_Plugin__c, Submission_Query_Plugin__c from Cognisureapi__mdt where DeveloperName ='api_details'];
        string fileuploadQueryPlugin = cognisureapimetadata.get('Email_Message_Query_Plugin__c')!=null?(String)cognisureapimetadata.get('Email_Message_Query_Plugin__c'):'CognisureAPI.MessageQueryBuilder';
        this.query = ((CognisureAPI.IMessageQueryHandler )Type.forName(fileuploadQueryPlugin).newInstance()).getMessageQuery();

    }

    public Database.QueryLocator start(Database.BatchableContext BC) {
        return Database.getQueryLocator(query);
    }

    public void execute(Database.BatchableContext BC, List<sObject> scope) {
        try {
            this.csapi = new CognisureAPIConsumerCtrl();
            List<Sobject> sobjlist = new List<Sobject>();
            for (SObject sobj : scope) {
                String sobjectId = (String) sobj.get('Id');

                String JSONResp = this.csapi.makeUploadRequestdo(sobjectId);
                System.debug(LoggingLevel.DEBUG, 'JSONResp:' + JSONResp);

                if(String.isBlank(JSONResp))
                    Throw New CSFileUploadAPIException('Empty Response from Server for File Upload');

                Sobject sobj_Submission = UploadAPIResponseProcessor.processJSONResponse(JSONResp);
                sobj_Submission.put('case__c', sobjectId);
                sobjlist.add(sobj_Submission);
                System.debug(LoggingLevel.DEBUG, JSON.serialize(sobjlist));
            }
            Insert sobjlist;
        } catch (Exception Ex) {
            Throw new CSFileUploadAPIException('Error Occured' + Ex.getStackTraceString() + Ex.getMessage());
        }
    }


    public void finish(Database.BatchableContext BC) {
        String jobName = 'File Upload Batch :' + Datetime.now();
        if (!test.isRunningTest())
            system.scheduleBatch(this, jobName, 1);

    }
}

/**
 *
 *
 *
 *
 *
  CSFileUploadAPIConsumerBatch cs = new CSFileUploadAPIConsumerBatch();
  Database.executeBatch(cs, 1);



 *
 *
 */